services:
  - type: web
    name: smart-stock-backend
    env: python
    pythonVersion: 3.10
    healthCheckPath: /health
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --workers 3 --bind 0.0.0.0:$PORT app:app --timeout 120