services:
  - type: web
    name: smart-stock-backend
    env: python
    pythonVersion: "3.10.12"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0